color: null
fieldLayouts:
  056213a6-5da0-4ee5-9169-1e3c124af4ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 00683567-59d7-4a3f-82c9-ed2a1b940b04
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fb1d8fd0-4411-4be2-bfe0-cff0a440e274 # Header Titel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0da8c97-6761-49e1-8ab7-685a425edc19
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: adf16fba-8454-4104-aeea-218979b59f28 # Contact Form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fcc32c8-a023-4915-a5a1-143d875d4e9e
            userCondition: null
            warning: null
            width: 100
        name: 'Contact Form'
        uid: 356c1415-3fa4-48b9-a52e-b60b47d5d4cf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fb1d8fd0-4411-4be2-bfe0-cff0a440e274 # Header Titel
            handle: headerTitel2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a3897d1-88c5-4009-a572-89af517afcc8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d83e91bf-5e17-4faf-85f6-cf0707e0ef3b # Nieuwsbrief Form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: decea4ba-45c9-4e88-bdc6-edbb0b878ebc
            userCondition: null
            warning: null
            width: 100
        name: Nieuwsbrief
        uid: 5caf573d-5334-4c9a-8510-a32a58d14797
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fb1d8fd0-4411-4be2-bfe0-cff0a440e274 # Header Titel
            handle: headerTitel3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bffdfac-4377-4a26-abcb-a9b2636e8c38
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 53b54b18-97b1-44d7-a3c6-d3d42695a567 # Mail
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32c2f2df-d2c3-40ec-a043-37e066c8a7b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 98a6f92c-170b-4702-a172-2f94801a3a43 # GSM Nummer
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45a0ddf4-0094-44a8-8a1e-90529c51aa25
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb5c4e4b-26b4-4570-8a74-46d95b330592 # Straat
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33f82f71-de62-425c-aa9a-09026489ee7d
            userCondition: null
            warning: null
            width: 100
        name: 'Contact Gegevens'
        uid: 9b03a294-8bcf-45c7-b766-2779fdbe0557
        userCondition: null
handle: contactpage
hasTitleField: true
icon: null
name: Contactpage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
