color: null
fieldLayouts:
  e7aab367-ae87-4ab0-b9ec-1542818e6595:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c6faac0f-56d5-40fb-9285-aa104817a98b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a0b203e-0bcb-4d1f-ba7c-eff8a05184fa
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75432cf4-6af6-43a7-8ce9-5f907f6a6701
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09c8ba78-54f0-46a9-a44d-88697c3384dc
        userCondition: null
handle: form
hasTitleField: false
icon: ''
name: Form
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Form block'
titleTranslationKeyFormat: null
titleTranslationMethod: site
