color: null
fieldLayouts:
  6502ada2-cd59-47c7-8ce2-c36f478bdcb5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f074513-eb74-49df-b241-5f9728e71fd5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fb1d8fd0-4411-4be2-bfe0-cff0a440e274
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e7ca964-521d-4c51-b1ce-d32a0583c35e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f8714083-bbd0-4185-b256-8742af4dad24 # Test
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ef880d3-c561-4d55-9b0c-c703438a2c05
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 52cda86a-aa53-481d-bfea-9647f2ebcf95
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d67bd74-5ae7-4320-8dab-fecf8dd5ce4e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37445816-133b-4529-8709-5190fd573747
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 115a8851-78f3-4809-9ceb-221d09eb2d12
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1ec28f21-ca85-424b-8648-1b509b3cf8ce
        userCondition: null
handle: homepageHeader
hasTitleField: true
icon: ''
name: 'Homepage Header'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
