color: null
fieldLayouts:
  60d08323-341c-4263-a3a7-c48e06a49353:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: 'Typ hier de titel van je pagina'
            label: 'Nieuwe Titel'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e5e20c7f-20dd-4cf2-b477-d9a931fca461
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2efad103-5850-43d1-b329-42a57939cbe0
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 184b5eef-bfc7-43c7-be6e-5273bf57246c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b468148-b299-4901-829f-c2edd1a0b95a
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b8b475e-d59a-48e8-8a3d-f78345759fad
            userCondition: null
            warning: null
            width: 100
        name: 'Tekst + Afbeelding'
        uid: f92ff28b-6c79-4b2e-a6a8-be482064d410
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8a0b203e-0bcb-4d1f-ba7c-eff8a05184fa
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d337c050-449a-4cf4-9b82-6be815f0cffc
            userCondition: null
            warning: null
            width: 100
        name: Formulier
        uid: bd94d6dd-5110-43ad-a003-560f85c1e6af
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2c00f778-72c4-4833-9cc5-c2d9d84c9bfc
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 037982bc-2a59-4a87-ba0b-a75285deb580
            userCondition: null
            warning: null
            width: 100
        name: 'Producten Blok'
        uid: aa03af72-172a-4b2d-87ca-a76b80b819e3
        userCondition: null
handle: maakPagina
hasTitleField: true
icon: ''
name: 'Maak Pagina aan'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
