color: null
fieldLayouts:
  73947ecd-f204-4425-8557-9097161759af:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f58b032a-3952-420a-b1f2-c96bcb48dbc8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e1d1f3e5-869c-460c-8113-231574d26416 # New Form Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20b97d98-6af1-44e4-bf0b-235efd0731f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e166e19-7e00-4c15-92ae-20928a7a688a # Form Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e9dac56-cb95-4322-b101-7d47a652b853
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a0b203e-0bcb-4d1f-ba7c-eff8a05184fa
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afd07ffd-e58c-44ce-b0be-c19013214906
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6c4bb674-c73d-4bae-8c8a-b05d30b15d0d
        userCondition: null
handle: newForm
hasTitleField: false
icon: ''
name: 'New Form'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Form Block'
titleTranslationKeyFormat: null
titleTranslationMethod: site
