color: null
fieldLayouts:
  bd86331a-7f2a-43cc-922a-1b05d9649d6b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 11e30fcc-efb8-4b58-909a-e36e4aa71eeb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2efad103-5850-43d1-b329-42a57939cbe0
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffb37f4b-8ec6-48cf-8f45-1753f7a155ae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d310102f-25ac-4e7b-947d-ad2440fb03da
        userCondition: null
handle: nieuweLanding
hasTitleField: false
icon: ''
name: 'Nieuwe Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Text Block'
titleTranslationKeyFormat: null
titleTranslationMethod: site
