color: null
fieldLayouts:
  79be781d-5b42-41a5-8c2a-1cefd907e644:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 07afe262-b85f-48f9-a6d9-1a5271aad716
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a0b203e-0bcb-4d1f-ba7c-eff8a05184fa
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a2d5bff-a6c3-4a1b-8666-aeaf2e6a9d9f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 89a372ea-642a-4227-81f7-1fb3127b27d6
        userCondition: null
handle: nieuweForm
hasTitleField: true
icon: ''
name: 'Nieuwe Form'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
