color: null
fieldLayouts:
  029fb0b4-46b2-41ab-a1c3-e633a784b494:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 98e0e927-131e-46c4-9069-c415c3beea42
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f8714083-bbd0-4185-b256-8742af4dad24 # Introductie Tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 078b7339-f016-4612-80d1-690d684a5588
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ee8c7348-b8d3-452f-b0c0-01382dce5078
        userCondition: null
handle: test
hasTitleField: true
icon: ''
name: Test
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
