color: null
fieldLayouts:
  28babbfe-8a37-4805-bdf3-73854f3171ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 69d35f64-e5fd-42e2-ab82-32fabdd1a6a5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 45503393-00b8-49b9-abfd-78c3f4b3e11f # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 392a4171-299a-4394-8434-8c673353dc57
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b1ee638a-5a29-4390-9d14-be2d36c167c0
        userCondition: null
handle: welcome
hasTitleField: true
icon: ''
name: Welcome
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
