baseUrl: '@baseUrl'
enabled: true
handle: default
hasUrls: true
language: en-US
name: Taro_Jan_Werkpakket3
primary: true
siteGroup: 09c3610b-7e94-41f2-a2cf-e82695b4ba2c # Taro_Jan_Werkpakket3
sortOrder: 1
