altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  24b15288-e963-4839-83df-b861e8a2980d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: bd63cf25-d2af-4b41-9ed5-51c019ba7918
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b0550e26-3c73-4e12-9552-8d2a57587c3c
        userCondition: null
fs: headerImage
handle: headerImage
name: 'Header Image'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
