altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  4b5988c7-3164-4217-8844-ad678b28bfc5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ad0f400d-fb9b-4dfb-8907-f3abe0a4f367
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 30e3b65c-5248-4a61-8cce-394fb1b75fef
        userCondition: null
fs: products
handle: products
name: Products
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
