columnSuffix: null
handle: newProductsBlock
instructions: "Choose 3 products you wqnt to show\r\n"
name: 'New Products Block'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 3
  minRelations: 3
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:183f5403-7918-4d1e-bbd8-25b120259ce6' # Product
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
