columnSuffix: null
handle: productPrice
instructions: 'How much does your product cost'
name: 'Product Price'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: '19.99'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
