columnSuffix: null
handle: productStock
instructions: null
name: 'Product Stock'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Stock: '
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
