columnSuffix: null
handle: releaseYear
instructions: 'Choose the release year and the company who produced the product'
name: Filters
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 2
  minRelations: 1
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:9a508750-43ce-4b63-ae4c-93c4079f23c6' # Release Years
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
