dateModified: 1716631678
email:
  fromEmail: 12102676@student.pxl.be
  fromName: Taro_Jan_Werkpakket3
  transportType: craft\mail\transportadapters\Sendmail
fs:
  headerImage:
    hasUrls: true
    name: 'Header Image'
    settings:
      path: '@webroot/header'
    type: craft\fs\Local
    url: '@baseUrl/header'
  nieuweAfbeeldingen:
    hasUrls: true
    name: 'Nieuwe Afbeeldingen'
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@baseUrl'
  products:
    hasUrls: true
    name: Products
    settings:
      path: '@webroot/products'
    type: craft\fs\Local
    url: '@baseUrl/products'
meta:
  __names__:
    0ddc8fe3-8a80-4f07-87cc-062bf8ddfcf6: 'Product Price' # Product Price
    1a68bcb2-b209-4c39-bf5d-f44664978609: Navbar # Navbar
    1ccb56f6-722a-4d88-a56c-01ae20e7d7d7: Adres # Adres
    1f528f49-8f4f-4edf-84b7-d80dfa593ba5: 'Nieuwe Pagina (voor content manager)' # Nieuwe Pagina (voor content manager)
    2a7768c8-a13e-4df0-b195-fa51e9645acf: shoppingpage # shoppingpage
    2c00f778-72c4-4833-9cc5-c2d9d84c9bfc: 'Nieuwe Populaire Producten' # Nieuwe Populaire Producten
    2efad103-5850-43d1-b329-42a57939cbe0: 'Nieuwe Tekst' # Nieuwe Tekst
    02fc9904-1bcf-413f-9c91-107b01d07adc: Year # Year
    3bed8216-16ac-401b-863f-1c8a0257a606: Telefoonnummer # Telefoonnummer
    4d9d9a2a-2f18-4120-a9fb-3ff1d4e78924: 'production Company' # production Company
    7b468148-b299-4901-829f-c2edd1a0b95a: 'Nieuwe Foto' # Nieuwe Foto
    8a0b203e-0bcb-4d1f-ba7c-eff8a05184fa: 'Nieuwe Form' # Nieuwe Form
    8d1c6bd8-76de-4a5c-9eb4-edde84820ba3: 'Nieuwe Afbeelding' # Nieuwe Afbeelding
    9a508750-43ce-4b63-ae4c-93c4079f23c6: 'Release Years' # Release Years
    09c3610b-7e94-41f2-a2cf-e82695b4ba2c: Taro_Jan_Werkpakket3 # Taro_Jan_Werkpakket3
    10c9bb8b-fdce-4665-8835-ed78a0d01ae4: 'Production company' # Production company
    22a19b0b-54e1-4c5c-9b18-fa4bf53cccc3: 'Production Company' # Production Company
    33f76516-a392-46f5-9c91-d4f15708f1ae: 'Shopping Page' # Shopping Page
    52cda86a-aa53-481d-bfea-9647f2ebcf95: 'Afbeelding Header' # Afbeelding Header
    53b54b18-97b1-44d7-a3c6-d3d42695a567: Mail # Mail
    69e3067d-55bc-4402-b9d5-87639c5a3263: 'Header Image' # Header Image
    87fde7cd-02f1-444b-9746-36ffea041512: Taro_Jan_Werkpakket3 # Taro_Jan_Werkpakket3
    96a473ad-0b7a-4a3f-878a-af8a5c259a6b: 'Sociale media' # Sociale media
    98a6f92c-170b-4702-a172-2f94801a3a43: 'GSM Nummer' # GSM Nummer
    183f5403-7918-4d1e-bbd8-25b120259ce6: Product # Product
    301e3e3a-4891-41e2-9a98-72e85b6482ff: 'Jaar van uitgave' # Jaar van uitgave
    759ad69a-d4f3-4a8c-9394-9feae4c8df23: Mailadres # Mailadres
    2685b248-da85-4b33-902d-ef8468f92c97: homepage # homepage
    3229ad84-ac51-4efc-b33a-9457de7c2e8e: 'Homepage Header' # Homepage Header
    6627b236-e5eb-42ef-bb61-0174d50fb165: 'Product Stock' # Product Stock
    45503393-00b8-49b9-abfd-78c3f4b3e11f: Description # Description
    a1356ef7-3612-4f92-8db8-24af453fedaf: Product # Product
    adf16fba-8454-4104-aeea-218979b59f28: 'Contact Form' # Contact Form
    b83a1e41-f048-4e4d-9ff2-71fe6067de34: 'Home Page' # Home Page
    bd208b06-b866-42b2-9e06-337e324ac776: 'Homepage tussentitel' # Homepage tussentitel
    be799785-5696-43d6-a6a8-42847acaaa55: 1980-1990 # 1980-1990
    c5afde39-203f-46b7-836f-759556a4c841: Contactpage # Contactpage
    c37668c3-44bd-42e8-bb53-d7a25fb8f515: Products # Products
    cb5c4e4b-26b4-4570-8a74-46d95b330592: Straat # Straat
    cc8b1d23-89d1-41d3-8956-bd972896da08: Footer # Footer
    d4c05d4c-7e4c-492c-981f-6d6d10b1b534: Filters # Filters
    d32fb5a3-3240-4a6e-8bd5-424f947e7719: 'Contact Form' # Contact Form
    d79f1b79-38ba-4ef3-b220-188e2ce51546: 'Product Description' # Product Description
    d83e91bf-5e17-4faf-85f6-cf0707e0ef3b: 'Nieuwsbrief Form' # Nieuwsbrief Form
    d745ad65-c9b0-4fc3-838e-324c75f466ed: New # New
    dbc84721-8df9-40e4-b822-595d51b33d69: 'Public Schema' # Public Schema
    df97fb95-f77f-4606-b7a8-a582bc3c0b17: 'Product Image' # Product Image
    e0b95ba0-8635-44b1-b56a-af94a3ad43ea: shoppingBanner # shoppingBanner
    e645c5de-ad7e-4d1e-a46d-2803f03cf11d: Instagram # Instagram
    f2bb5775-4a01-452b-9d65-a133844faa38: 'Maak Pagina aan' # Maak Pagina aan
    f8714083-bbd0-4185-b256-8742af4dad24: 'Introductie Tekst' # Introductie Tekst
    fb1d8fd0-4411-4be2-bfe0-cff0a440e274: 'Header Titel' # Header Titel
    fbfb433a-22bb-4c33-8332-9381883c5955: Contactpage # Contactpage
    fc2961ce-a588-41e7-b4f5-3af53942dcaa: contact # contact
plugins:
  cookie-consent:
    edition: standard
    enabled: true
    licenseKey: QG5NTQLKMK2H4XE6ZPB4MYA4
    schemaVersion: 1.5.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: VIJCBRO9PUJMEPA0RD767078
    schemaVersion: 3.4.4
  navigate:
    edition: standard
    enabled: true
    licenseKey: H0C49BER5M1EB136Y1QACTMY
    schemaVersion: 2.4.0
system:
  edition: pro
  live: true
  name: Taro_Jan_Werkpakket3
  retryDuration: null
  schemaVersion: 5.0.0.20
  timeZone: Europe/Brussels
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
