dateModified: 1715682389
email:
  fromEmail: 12102676@student.pxl.be
  fromName: Taro_Jan_Werkpakket3
  transportType: craft\mail\transportadapters\Sendmail
fs:
  products:
    hasUrls: false
    name: Products
    settings:
      path: '@webroot/products'
    type: craft\fs\Local
    url: '@webroot'
meta:
  __names__:
    2cb09214-a2df-47c9-a3cc-13710bb8eda6: Welcome # Welcome
    09c3610b-7e94-41f2-a2cf-e82695b4ba2c: Taro_Jan_Werkpakket3 # Taro_Jan_Werkpakket3
    10c5c643-5200-4e58-9b01-8b97bddaf174: Test # Test
    87fde7cd-02f1-444b-9746-36ffea041512: Taro_Jan_Werkpakket3 # Taro_Jan_Werkpakket3
    96a473ad-0b7a-4a3f-878a-af8a5c259a6b: 'Sociale media' # Sociale media
    183f5403-7918-4d1e-bbd8-25b120259ce6: Product # Product
    0647c999-ab04-4909-8fd1-781a924c571d: 'Welcome Message' # Welcome Message
    6627b236-e5eb-42ef-bb61-0174d50fb165: 'Product Stock' # Product Stock
    45503393-00b8-49b9-abfd-78c3f4b3e11f: Description # Description
    a1356ef7-3612-4f92-8db8-24af453fedaf: Product # Product
    b2fc564b-a147-4201-91b5-46adefdef1db: Test # Test
    c37668c3-44bd-42e8-bb53-d7a25fb8f515: Products # Products
    dbc84721-8df9-40e4-b822-595d51b33d69: 'Public Schema' # Public Schema
    df97fb95-f77f-4606-b7a8-a582bc3c0b17: 'Product Image' # Product Image
    e645c5de-ad7e-4d1e-a46d-2803f03cf11d: Instagram # Instagram
    f8714083-bbd0-4185-b256-8742af4dad24: Test # Test
plugins:
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigate:
    edition: standard
    enabled: true
    licenseKey: H0C49BER5M1EB136Y1QACTMY
    schemaVersion: 2.4.0
system:
  edition: pro
  live: true
  name: Taro_Jan_Werkpakket3
  retryDuration: null
  schemaVersion: 5.0.0.20
  timeZone: Europe/Brussels
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
