defaultPlacement: end
enableVersioning: true
entryTypes:
  - 345bf929-5569-4d28-85c7-abe2c4a6c117 # Page builder
handle: newPage
maxAuthors: 1
name: 'New Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  87fde7cd-02f1-444b-9746-36ffea041512: # Taro_Jan_Werkpakket3
    enabledByDefault: true
    hasUrls: true
    template: pages/_content-managerPage.twig
    uriFormat: new-page
structure:
  maxLevels: null
  uid: 9d0fd0bc-d861-41c3-b037-08f984d704c5
type: structure
