defaultPlacement: end
enableVersioning: true
entryTypes:
  - f2bb5775-4a01-452b-9d65-a133844faa38 # Maak Pagina aan
handle: nieuwePagina
maxAuthors: 1
name: 'Nieuwe Pagina (voor content manager)'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  87fde7cd-02f1-444b-9746-36ffea041512: # Taro_Jan_Werkpakket3
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
