defaultPlacement: end
enableVersioning: true
entryTypes:
  - a1356ef7-3612-4f92-8db8-24af453fedaf # Product
handle: product
maxAuthors: 1
name: Product
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  87fde7cd-02f1-444b-9746-36ffea041512: # Taro_Jan_Werkpakket3
    enabledByDefault: true
    hasUrls: true
    template: components/_products.twig
    uriFormat: 'product/{slug}'
type: channel
