defaultPlacement: end
enableVersioning: true
entryTypes:
  - e0b95ba0-8635-44b1-b56a-af94a3ad43ea # shoppingBanner
handle: shoppingPage
maxAuthors: 1
name: 'Shopping Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  87fde7cd-02f1-444b-9746-36ffea041512: # Taro_Jan_Werkpakket3
    enabledByDefault: true
    hasUrls: true
    template: pages\_shoppingpage.twig
    uriFormat: shopping-page
type: single
