defaultPlacement: end
enableVersioning: true
entryTypes:
  - b2fc564b-a147-4201-91b5-46adefdef1db # Test
handle: test
maxAuthors: 1
name: Test
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  87fde7cd-02f1-444b-9746-36ffea041512: # Taro_Jan_Werkpakket3
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
