defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2cb09214-a2df-47c9-a3cc-13710bb8eda6 # Welcome
handle: welcomeMessage
maxAuthors: 1
name: 'Welcome Message'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  87fde7cd-02f1-444b-9746-36ffea041512: # Taro_Jan_Werkpakket3
    enabledByDefault: true
    hasUrls: true
    template: welcome-message/_entry
    uriFormat: 'welcome-message/{slug}'
type: channel
